### ISSUE TITLE
Illegal instruction error

### ISSUE THREAD

**Issue by jimmylegendary** [ECP-copa/CabanaMD#105]
As I run cbnmd binary, there is Illegal instruction error
So, I tried to test  unit_test, but there is  also same error

I attached log when running Neighbor_test_SERIAL with gdb

Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-127.el8.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments

Program received signal SIGILL, Illegal instruction.
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*> (__end=<optimized out>, __beg=<synthetic pointer>, this=0x7fffffffced0)
    at /usr/include/c++/8/bits/basic_string.tcc:225
225               { this->_S_copy_chars(_M_data(), __beg, __end); }
Missing separate debuginfos, use: yum debuginfo-install libgcc-8.3.1-5.1.el8.x86_64 libgomp-8.3.1-5.1.el8.x86_64 libstdc++-8.3.1-5.1.el8.x86_64 nvidia-driver-cuda-libs-470.57.02-1.el8.x86_64 zlib-1.2.11-16.el8_2.x86_64

**Comment by streeve** [comment]
Can you post your CMake configuration and details of the machine you're running on?

**Comment by streeve** [comment]
Feel free to reopen with new information if there are continuing issues
