### ISSUE TITLE
CMake 3.11+ required for build?

### ISSUE THREAD

**Issue by singraber** [ECP-copa/CabanaMD#66]
This is only a minor issue which can probably be fixed by simply updating the documentation:

When setting up the CabanaMD build with `cmake` it fails with this error:

```
CMake Error at CMakeLists.txt:19 (include):
  include could not find load file:

    FetchContent


CMake Error at CMakeLists.txt:20 (FetchContent_Declare):
  Unknown CMake command "FetchContent_Declare".
```
I think the reason is a too old version of `cmake`: The [`FetchContent_Declare`](https://cmake.org/cmake/help/v3.11/module/FetchContent.html) command appears in `cmake` 3.11 whereas I am currently using 3.10.2. The CabanaMD [documentation](https://github.com/ECP-copa/CabanaMD/wiki/Build-Instructions#dependencies) says that even 3.9+ would be sufficient.

I will update my `cmake` and see whether this will resolve the issue...

**Comment by dalg24** [comment]
You are correct.  See #65

**Comment by singraber** [comment]
Updating `cmake` to 3.18.1 resolved the issue, sorry for double-posting this...

**Comment by dalg24** [comment]
> Updating `cmake` to 3.18.1 resolved the issue, sorry for double-posting this...

No need to apologize!  Thanks for reporting the issue and sorry about the inconvenience.  I expect the fix will be merged shortly.
