### ISSUE TITLE
Replace n2p2 master with tagged release

### ISSUE THREAD

**Issue by streeve** [ECP-copa/CabanaMD#83]
Once available, use tagged release (including CabanaMD interface) of n2p2 in CI

**Comment by streeve** [comment]
Brought up in CompPhysVienna/n2p2#32

**Comment by singraber** [comment]
n2p2 release version 2.0.1 is now available here:

https://github.com/CompPhysVienna/n2p2/releases/tag/v2.0.1

I will create release tags more frequently from now on and will mostly adhere to the "semantic versioning" rules.
